#count the number of possible coding sequences generated by a single DNA sequence
#create a string variable to store the sequence
seq = 'ATGCAATCGACTACGATCTGAGAGGGCCTAA'
#firstly count the number of each individual stop codon
#add them up
#count the total number of possible coding sequences formed by the sequence
TAA = seq.count('TAA')
TAG = seq.count('TAG')
TGA = seq.count('TGA')
total_number = TAA + TAG + TGA
print('The total number of possible coding sequences formed by the sequence is', total_number)